spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:gestion_fitpower;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update # Para desarrollo, crea el esquema al iniciar y lo borra al parar.

  # Kafka Producer Configuration
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

server:
  port: 8080