spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  jwt:
    secret: ${SECRET_KEY}

server:
  port: 8081

logging:
  level:
    root: info
